%YAML 1.2
---
# This dotdrop config file is meant for shell-related, user-independent
# profiles.

actions:
  install_yay: yay -S --needed --noconfirm --useask {0}
  pre:
    install-prompt: install_yay "starship-bin"
  post:
    bash: bash ./actions/bash.sh "{{@@ dotdirs_file @@}}"
    sh: sh ./actions/sh.sh "{{@@ dotdirs_file @@}}"
    zsh: zsh ./actions/zsh.zsh "{{@@ dotdirs_file @@}}"
    loginstall: echo bdotdir "{{@@ xdg_config("bash") @@}}"

config:
  backup: false
  banner: true
  create: true
  dotpath: ../../dotfiles
  filter_file:
  - ../../python/filters.py
  func_file:
  - ../../python/functions.py
  ignoreempty: true
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  showdiff: true
  workdir: '{{@@ xdg_config("dotdrop") @@}}'

dotfiles:
  f_profile:
    src: shell/profile
    dst: ~/.profile
  f_aliases:
    src: shell/aliases
    dst: ~/.aliases
    link: nolink
  f_inputrc:
    src: bash/inputrc
    dst: ~/.config/inputrc
  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash/bash_profile
    dst: ~/.bash_profile
  f_bash_prompt:
    src: bash/bash_prompt
    dst: ~/.bash_prompt
  f_bash_completion:
    src: bash/bash_completion
    dst: ~/.bash_completion
  f_bash_logout:
    src: bash/bash_logout
    dst: ~/.bash_logout
  d_completions:
    src: bash/completions
    dst: ~/.config/bash/completions

  d_bash:
    src: config/bash
    # Dynamic path as it's used somewhere else too
    dst: '{{@@ bdotdir @@}}'
    upignore:
    - .bash_history
    - cache
  d_zsh:
    src: config/zsh
    # Dynamic path as it's used somewhere else too
    dst: '{{@@ zdotdir @@}}'
    upignore:
    - .zcompdump
    - .zsh_history
    - .antibody
    - cache
    - 'plugins/plugins-*.zsh'

  f_dotdirs:
    src: config/dotdirs
    # Dynamic path as it's used somewhere else too
    dst: '{{@@ dotdirs_file @@}}'

profiles:
  shell:
    dotfiles:
    - f_profile
    - f_aliases

  bash:
    dotfiles:
    - f_inputrc
    - f_bashrc
    - f_bash_profile
    - f_bash_prompt
    - f_bash_logout
    - d_completions
    include:
    - shell
    actions:
    - loginstall

  zsh:
    dotfiles:
    - d_zsh
    include:
    - shell
    actions:
    - zsh

variables:
  # These paths are variables because they are used in multiple places,
  # such as templates, dotfile entries dst and action arguments.
  bdotdir: '{{@@ xdg_config("bash") @@}}'
  sdotdir: '{{@@ xdg_config("sh") @@}}'
  zdotdir: '{{@@ xdg_config("zsh") @@}}'
  dotdirs_file: '{{@@ xdg_config("dotdirs") @@}}'
